# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'PromiseDemo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PromiseDemo
  pod 'PromiseKit', '~> 3.4'

  #AlamofireImage is an image component library for Alamofire.
  pod 'AlamofireImage', '~> 2.0'

  #ObjectMapper is a framework written in Swift that makes it easy
   #for you to convert your model objects (classes and structs) to and from JSON.
   pod 'ObjectMapper', '~> 1.2'

end
